version: '3'
# container_name: 'test'

services:
    core-api:
        image: 'node:8.12.0-alpine'
        working_dir: '/home/core-api'
        container_name: 'test'
        volumes:
          - ./:/home/core-api
        command: "sh -c 'npm install && npm run dev'"
        environment:
          NODE_ENV: development
        ports:
          - 3000:3000
